services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\Users\Conditional\Posts\Hooks\:
        resource: '../../../src/Conditional/Posts/Hooks/*'
        public: true

    PoP\Users\Conditional\Posts\Conditional\API\RouteModuleProcessors\:
        resource: '../../../src/Conditional/Posts/Conditional/API/RouteModuleProcessors/*'
        public: true

    PoP\Users\Conditional\Posts\Conditional\RESTAPI\RouteModuleProcessors\:
        resource: '../../../src/Conditional/Posts/Conditional/RESTAPI/RouteModuleProcessors/*'
        public: true
