services:
    PoP\Users\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Users\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true

    PoP\Users\Conditional\Posts\FieldResolvers\:
        resource: '../src/Conditional/Posts/FieldResolvers/*'
        public: true
