services:
    PoP\Users\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Users\TypeResolvers\:
        resource: '../src/TypeResolvers/*'
        public: true
