parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\Users\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Users\Conditional\Posts\FieldResolvers\:
        resource: '../src/Conditional/Posts/FieldResolvers/*'
        public: true

    PoP\Users\Conditional\API\RouteModuleProcessors\:
        resource: '../src/Conditional/API/RouteModuleProcessors/*'
        public: true

    PoP\Users\Conditional\RESTAPI\RouteModuleProcessors\:
        resource: '../src/Conditional/RESTAPI/RouteModuleProcessors/*'
        public: true

    PoP\Users\Conditional\Posts\Hooks\:
        resource: '../src/Conditional/Posts/Hooks/*'
        public: true

    PoP\Users\Conditional\Posts\Conditional\API\RouteModuleProcessors\:
        resource: '../src/Conditional/Posts/Conditional/API/RouteModuleProcessors/*'
        public: true

    PoP\Users\Conditional\Posts\Conditional\RESTAPI\RouteModuleProcessors\:
        resource: '../src/Conditional/Posts/Conditional/RESTAPI/RouteModuleProcessors/*'
        public: true
